In [77]:
import csv
import numpy as np
from nltk.tokenize import sent_tokenize, word_tokenize, WhitespaceTokenizer
import warnings
import gensim
from gensim.models import Word2Vec, KeyedVectors
import pandas as pd

In [2]:
in_domain_train = open("../dataset/cola_public_1.1/cola_public/raw/in_domain_train.tsv")
in_domain_train_tokenized = open("../dataset/cola_public_1.1/cola_public/tokenized/in_domain_train.tsv")
in_domain_dev_tokenized = open("../dataset/cola_public_1.1/cola_public/tokenized/in_domain_dev.tsv")
in_domain_test = open("../dataset/cola-in-domain-open-evaluation/cola_in_domain_test.tsv")

In [3]:
read_train = csv.reader(in_domain_train_tokenized, delimiter="\t")
train = []
for row in read_train:
    train.append(row)

In [5]:
in_domain_train_tokenized.close()

In [4]:
read_dev = csv.reader(in_domain_dev_tokenized, delimiter="\t")
dev = []
for row in read_dev:
    dev.append(row)

In [6]:
in_domain_dev_tokenized.close()

In [45]:
read_test = csv.reader(in_domain_test, delimiter="\t")
test = []
for row in read_test:
    test.append(row)

In [46]:
in_domain_test.close()

In [7]:
train

[['gj04',
  '1',
  '',
  "our friends wo n't buy this analysis , let alone the next one we propose ."],
 ['gj04', '1', '', "one more pseudo generalization and i 'm giving up ."],
 ['gj04', '1', '', "one more pseudo generalization or i 'm giving up ."],
 ['gj04', '1', '', 'the more we study verbs , the crazier they get .'],
 ['gj04', '1', '', 'day by day the facts are getting murkier .'],
 ['gj04', '1', '', "i 'll fix you a drink ."],
 ['gj04', '1', '', 'fred watered the plants flat .'],
 ['gj04', '1', '', 'bill coughed his way out of the restaurant .'],
 ['gj04', '1', '', "we 're dancing the night away ."],
 ['gj04', '1', '', 'herman hammered the metal flat .'],
 ['gj04', '1', '', 'the critics laughed the play off the stage .'],
 ['gj04', '1', '', 'the pond froze solid .'],
 ['gj04', '1', '', 'bill rolled out of the room .'],
 ['gj04', '1', '', 'the gardener watered the flowers flat .'],
 ['gj04', '1', '', 'the gardener watered the flowers .'],
 ['gj04', '1', '', 'bill broke the bathtu

In [8]:
dev

[['gj04', '1', '', 'the sailors rode the breeze clear of the rocks .'],
 ['gj04', '1', '', 'the weights made the rope stretch over the pulley .'],
 ['gj04', '1', '', 'the mechanical doll wriggled itself loose .'],
 ['cj99', '1', '', 'if you had eaten more , you would want less .'],
 ['cj99', '0', '*', 'as you eat the most , you want the least .'],
 ['cj99', '0', '*', 'the more you would want , the less you would eat .'],
 ['cj99', '0', '*', 'i demand that the more john eat , the more he pays .'],
 ['cj99', '1', '', 'mary listens to the grateful dead , she gets depressed .'],
 ['cj99', '1', '', 'the angrier mary got , the more she looked at pictures .'],
 ['cj99', '1', '', 'the higher the stakes , the lower his expectations are .'],
 ['cj99',
  '1',
  '',
  'the more fred is obnoxious , the less attention you should pay to him .'],
 ['cj99', '1', '', 'john was lots more obnoxious than fred .'],
 ['cj99',
  '1',
  '',
  'the more people you give beer to , the more people get sick .'],
 [

In [47]:
test

[['Id', 'Sentence'],
 ['1', 'Bill whistled past the house.'],
 ['2', 'The car honked its way down the road.'],
 ['3', 'Bill pushed Harry off the sofa.'],
 ['4', 'the kittens yawned awake and played.'],
 ['5', 'I demand that the more John eats, the more he pay.'],
 ['6', 'If John eats more, keep your mouth shut tighter, OK?'],
 ['7', 'His expectations are always lower than mine are.'],
 ['8', 'The sooner you call, the more carefully I will word the letter.'],
 ['9',
  'The more timid he feels, the more people he interviews without asking questions of.'],
 ['10', 'Once Janet left, Fred became a lot crazier.'],
 ['11',
  'If you give every senator enough opportunity, he will succumb to corruption.'],
 ['12',
  'The more time that any senator spends with lobbyists, the more likely he is to succumb to corruption.'],
 ['13',
  "Which problem does the sooner you solve, the more easily you'll satisfy the folks up at corporate headquarters?"],
 ['14',
  "Which problem do you think that the soon

In [9]:
train_array = np.array(train)
train_df = pd.DataFrame(train_array)
train_df

0  1  2                                                  3
0     gj04  1     our friends wo n't buy this analysis , let alo...
1     gj04  1     one more pseudo generalization and i 'm giving...
2     gj04  1     one more pseudo generalization or i 'm giving ...
3     gj04  1      the more we study verbs , the crazier they get .
4     gj04  1            day by day the facts are getting murkier .
...    ... .. ..                                                ...
8546  ad03  0  *                   poseidon appears to own a dragon
8547  ad03  0  *                     digitize is my happiest memory
8548  ad03  1                       it is easy to slay the gorgon .
8549  ad03  1         i had the strangest feeling that i knew you .
8550  ad03  1                  what all did you get for christmas ?

[8551 rows x 4 columns]

In [10]:
dev_array = np.array(dev)
dev_df = pd.DataFrame(dev_array)
dev_df

0  1  2                                                  3
0    gj04  1      the sailors rode the breeze clear of the rocks .
1    gj04  1     the weights made the rope stretch over the pul...
2    gj04  1           the mechanical doll wriggled itself loose .
3    cj99  1         if you had eaten more , you would want less .
4    cj99  0  *         as you eat the most , you want the least .
..    ... .. ..                                                ...
522  ad03  0  *                         i would like to could swim
523  ad03  1                                       i kicked myself
524  ad03  0  *                                   the bookcase ran
525  ad03  1                                     i shaved myself .
526  ad03  0  *                      anson became a muscle bound .

[527 rows x 4 columns]

In [48]:
test_array = np.array(test)
test_df = pd.DataFrame(test_array)
test_df

0                                                  1
0     Id                                           Sentence
1      1                      Bill whistled past the house.
2      2              The car honked its way down the road.
3      3                    Bill pushed Harry off the sofa.
4      4               the kittens yawned awake and played.
..   ...                                                ...
526  526  There were people eating fire at the fair, wer...
527  527       Jason would prefer to have cursed Agamemnon.
528  528                                        Anson joked
529  529          Gilgamesh may quickly have cast the spell
530  530          Which book about himself did Anson write?

[531 rows x 2 columns]

In [11]:
list_sent_train = [row[3] for row in train]
list_sent_train

["our friends wo n't buy this analysis , let alone the next one we propose .",
 "one more pseudo generalization and i 'm giving up .",
 "one more pseudo generalization or i 'm giving up .",
 'the more we study verbs , the crazier they get .',
 'day by day the facts are getting murkier .',
 "i 'll fix you a drink .",
 'fred watered the plants flat .',
 'bill coughed his way out of the restaurant .',
 "we 're dancing the night away .",
 'herman hammered the metal flat .',
 'the critics laughed the play off the stage .',
 'the pond froze solid .',
 'bill rolled out of the room .',
 'the gardener watered the flowers flat .',
 'the gardener watered the flowers .',
 'bill broke the bathtub into pieces .',
 'bill broke the bathtub .',
 'they drank the pub dry .',
 'they drank the pub .',
 'the professor talked us into a stupor .',
 'the professor talked us .',
 'we yelled ourselves hoarse .',
 'we yelled ourselves .',
 'we yelled harry hoarse .',
 'harry coughed himself into a fit .',
 'harry

In [12]:
list_sent_dev = [row[3] for row in dev]
list_sent_dev

['the sailors rode the breeze clear of the rocks .',
 'the weights made the rope stretch over the pulley .',
 'the mechanical doll wriggled itself loose .',
 'if you had eaten more , you would want less .',
 'as you eat the most , you want the least .',
 'the more you would want , the less you would eat .',
 'i demand that the more john eat , the more he pays .',
 'mary listens to the grateful dead , she gets depressed .',
 'the angrier mary got , the more she looked at pictures .',
 'the higher the stakes , the lower his expectations are .',
 'the more fred is obnoxious , the less attention you should pay to him .',
 'john was lots more obnoxious than fred .',
 'the more people you give beer to , the more people get sick .',
 'the more does bill smoke , the more susan hates him .',
 'the more pictures of him that appear in the news , the more embarrassed john becomes .',
 'every senator seems to become more corrupt , as he talks to more lobbyists .',
 'who does john visit sally becaus

In [13]:
list_sent_train_tkn = []

for sent in list_sent_train:
    list_sent_train_tkn.append(word_tokenize(sent))

list_sent_train_tkn

[['our',
  'friends',
  'wo',
  "n't",
  'buy',
  'this',
  'analysis',
  ',',
  'let',
  'alone',
  'the',
  'next',
  'one',
  'we',
  'propose',
  '.'],
 ['one',
  'more',
  'pseudo',
  'generalization',
  'and',
  'i',
  "'m",
  'giving',
  'up',
  '.'],
 ['one',
  'more',
  'pseudo',
  'generalization',
  'or',
  'i',
  "'m",
  'giving',
  'up',
  '.'],
 ['the',
  'more',
  'we',
  'study',
  'verbs',
  ',',
  'the',
  'crazier',
  'they',
  'get',
  '.'],
 ['day', 'by', 'day', 'the', 'facts', 'are', 'getting', 'murkier', '.'],
 ['i', "'ll", 'fix', 'you', 'a', 'drink', '.'],
 ['fred', 'watered', 'the', 'plants', 'flat', '.'],
 ['bill', 'coughed', 'his', 'way', 'out', 'of', 'the', 'restaurant', '.'],
 ['we', "'re", 'dancing', 'the', 'night', 'away', '.'],
 ['herman', 'hammered', 'the', 'metal', 'flat', '.'],
 ['the', 'critics', 'laughed', 'the', 'play', 'off', 'the', 'stage', '.'],
 ['the', 'pond', 'froze', 'solid', '.'],
 ['bill', 'rolled', 'out', 'of', 'the', 'room', '.'],
 ['the

In [14]:
list_sent_dev_tkn = []

for sent in list_sent_dev:
    list_sent_dev_tkn.append(word_tokenize(sent))

list_sent_dev_tkn

[['the',
  'sailors',
  'rode',
  'the',
  'breeze',
  'clear',
  'of',
  'the',
  'rocks',
  '.'],
 ['the',
  'weights',
  'made',
  'the',
  'rope',
  'stretch',
  'over',
  'the',
  'pulley',
  '.'],
 ['the', 'mechanical', 'doll', 'wriggled', 'itself', 'loose', '.'],
 ['if',
  'you',
  'had',
  'eaten',
  'more',
  ',',
  'you',
  'would',
  'want',
  'less',
  '.'],
 ['as', 'you', 'eat', 'the', 'most', ',', 'you', 'want', 'the', 'least', '.'],
 ['the',
  'more',
  'you',
  'would',
  'want',
  ',',
  'the',
  'less',
  'you',
  'would',
  'eat',
  '.'],
 ['i',
  'demand',
  'that',
  'the',
  'more',
  'john',
  'eat',
  ',',
  'the',
  'more',
  'he',
  'pays',
  '.'],
 ['mary',
  'listens',
  'to',
  'the',
  'grateful',
  'dead',
  ',',
  'she',
  'gets',
  'depressed',
  '.'],
 ['the',
  'angrier',
  'mary',
  'got',
  ',',
  'the',
  'more',
  'she',
  'looked',
  'at',
  'pictures',
  '.'],
 ['the',
  'higher',
  'the',
  'stakes',
  ',',
  'the',
  'lower',
  'his',
  'expec

In [ ]:
list_sent_test_tkn = []

for sent in list_sent_test:
    list_sent_test_tkn.append(word_tokenize(sent))

In [15]:
list_sent_tkn = list_sent_train_tkn + list_sent_dev_tkn

In [17]:
len(list_sent_tkn)

9078

In [111]:
model1 = Word2Vec(sentences=list_sent_tkn,vector_size=300,window=10,min_count=1)
w2v_model = Word2Vec(list_sent_tkn, min_count=1, vector_size= 50, workers=3, window =3, sg = 1)
word2vec_model = KeyedVectors.load_word2vec_format('embedding.txt', binary=False)
word2vec_model

In [128]:
words = list(word2vec_model.index_to_key)
# words = list(w2v_model.wv.index_to_key)

# print(words)
print(len(words))

14532


In [113]:
print(words)

['reference', 'que', 'anytime', 'intertainments', 'Raisa', 'meaby', 'Upper', 'die', 'handicapt', 'clothing', 'attractions', 'straigh', 'beers', 'disadvantages.', 'POLITICIANS', 'rivers', 'towers', 'heating', 'beaten', 'excluding', 'CULTURS', 'theire', 'excepted', 'harmful', 'Pabori', 'coleagues', 'planning', '23th', 'PROBABLY', 'detectives', 'evite', 'rubbers', 'skirt', 'apparently', 'Savage', 'earthquake', 'post', 'orient', 'KNOW', '2:30', 'mack', 'Picking', 'Murasaki', 'invent', 'litterature', 'enougher', 'Tommy', 'Thankeaw', 'european', 'Torroja', 'Maths', 'schems', 'masterpiece', 'the', 'scholl', 'equipments', 'Thanasukolwit', 'deferent', 'absuletely', 'gossiping', 'photographer', 'montage', 'seat', 'Martel', 'untouchable', "I'am", 'inventions', 'cannot', 'hundreds', 'answer', 'printed', 'identity', 'Take', 'advert', 'paparachi', 'fashioned-clothes', 'BLOCK', 'un', 'exitation', 'campsite', 'divorsed', 'baseball', 'haircut', 'Alice', 'Breaks', 'desappointing', 'easyer', 'whot', 'toy

In [114]:
word_vec_dict={}
for word in words:
    word_vec_dict[word]=word2vec_model.get_vector(word)
print("The no of key-value pairs : ",len(word_vec_dict)) # should come equal to vocab size

The no of key-value pairs :  14532


In [115]:
w2v_weights = word2vec_model.vectors
vocab_size, embedding_size = w2v_weights.shape
print(vocab_size, embedding_size)
MAX_SEQUENCE_LENGTH = 200

14532 300


In [116]:
from keras.models import Sequential
from keras.layers import *
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from keras.initializers import Constant
import gensim
import sys
import numpy as np
import pandas as pd
import string
import logging
import random
import keras
import matplotlib.pyplot as plt

In [117]:
# df = train_df.append(dev_df)
df = pd.concat([train_df, dev_df])

In [118]:
df

0  1  2                                                  3
0    gj04  1     our friends wo n't buy this analysis , let alo...
1    gj04  1     one more pseudo generalization and i 'm giving...
2    gj04  1     one more pseudo generalization or i 'm giving ...
3    gj04  1      the more we study verbs , the crazier they get .
4    gj04  1            day by day the facts are getting murkier .
..    ... .. ..                                                ...
522  ad03  0  *                         i would like to could swim
523  ad03  1                                       i kicked myself
524  ad03  0  *                                   the bookcase ran
525  ad03  1                                     i shaved myself .
526  ad03  0  *                      anson became a muscle bound .

[9078 rows x 4 columns]

In [129]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical


maxi=-1
for i,rev in enumerate(df[3]):
  tokens=rev.split()
  if(len(tokens)>maxi):
    maxi=len(tokens)


tok = Tokenizer(filters='')
tok.fit_on_texts(df[3])
vocab_size = len(tok.word_index) + 1
train_encd_rev = tok.texts_to_sequences(train_df[3])
dev_encd_rev = tok.texts_to_sequences(dev_df[3])

print(vocab_size)

5524


In [121]:
# now padding to have a amximum length of 44
train_pad_rev= pad_sequences(train_encd_rev, maxlen=maxi+1, padding='post')
train_pad_rev.shape   # note that we had 100K reviews and we have padded each review to have  a lenght of 1565 words.
print(train_pad_rev)
print(train_pad_rev.shape)

[[ 239  280  250 ...    0    0    0]
 [  82   31 2703 ...    0    0    0]
 [  82   31 2703 ...    0    0    0]
 ...
 [  17    7  183 ...    0    0    0]
 [   5   44    2 ...    0    0    0]
 [  49   60   20 ...    0    0    0]]
(8551, 45)


In [122]:
dev_pad_rev= pad_sequences(dev_encd_rev, maxlen=maxi+1, padding='post')
dev_pad_rev.shape   # note that we had 100K reviews and we have padded each review to have  a lenght of 1565 words.
print(dev_pad_rev)
print(dev_pad_rev.shape)

[[   2 3090 2108 ...    0    0    0]
 [   2 2195  109 ...    0    0    0]
 [   2 5425 2034 ...    0    0    0]
 ...
 [   2 5522  344 ...    0    0    0]
 [   5  823  253 ...    0    0    0]
 [ 195  259    4 ...    0    0    0]]
(527, 45)


In [123]:
# now creating the embedding matrix
embed_matrix=np.zeros(shape=(vocab_size,embedding_size))
print(len(tok.word_index.items()))
for word,i in tok.word_index.items():
  embed_vector=word_vec_dict.get(word)
  if embed_vector is not None:  # word is in the vocabulary learned by the w2v model
    embed_matrix[i]=embed_vector
  # if word is not found then embed_vector corressponding to that vector will stay zero.

train_size=0.8

X_train = train_pad_rev
X_validation = dev_pad_rev

y_train = to_categorical(train_df[1])  # one hot target as required by NN
y_validation = to_categorical(dev_df[1])


print(X_train.shape), print(y_train.shape)
print(X_validation.shape), print(y_validation.shape)
# print(X_test.shape), print(y_test.shape)

5523
(8551, 45)
(8551, 2)
(527, 45)
(527, 2)


(None, None)

In [124]:
leinst = LabelEncoder()
leinst.fit_transform(df[1])

num_classes = len(leinst.classes_)
print(num_classes)
print(leinst.classes_)

2
['0' '1']


In [130]:
print(w2v_weights.shape)

(14532, 300)


In [132]:
print(embedding_size)
test = []

model = Sequential()
print(y_train)
# Keras Embedding layer with Word2Vec weights initialization
model.add(Embedding(input_dim=vocab_size,
                    output_dim=embedding_size,
                    weights=[embed_matrix],
                    input_length=45,
                    ))

model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))
model.add(Flatten())
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=10, batch_size=32,
                    validation_data=(X_validation, y_validation), verbose=1)

300
[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Epoch 1/10
268/268 [==============================] - 42s 144ms/step - loss: 0.6100 - accuracy: 0.7019 - val_loss: 0.6081 - val_accuracy: 0.6945
Epoch 2/10
268/268 [==============================] - 37s 140ms/step - loss: 0.5654 - accuracy: 0.7161 - val_loss: 0.6077 - val_accuracy: 0.6869
Epoch 3/10
268/268 [==============================] - 37s 139ms/step - loss: 0.4953 - accuracy: 0.7523 - val_loss: 0.6475 - val_accuracy: 0.6812
Epoch 4/10
268/268 [==============================] - 37s 138ms/step - loss: 0.4282 - accuracy: 0.7838 - val_loss: 0.7143 - val_accuracy: 0.6622
Epoch 5/10
268/268 [==============================] - 39s 144ms/step - loss: 0.3744 - accuracy: 0.8160 - val_loss: 0.7915 - val_accuracy: 0.6546
Epoch 6/10
268/268 [==============================] - 40s 149ms/step - loss: 0.3278 - accuracy: 0.8410 - val_loss: 0.8990 - val_accuracy: 0.6433
Epoch 7/10
268/268 [==============================] - 39s 146ms/st

In [136]:
model2 = Sequential()

# Keras Embedding layer with Word2Vec weights initialization
model2.add(Embedding(input_dim=vocab_size,
                    output_dim=embedding_size,
                    weights=[embed_matrix],
                    input_length=45,
                    mask_zero=True,
                    trainable=False))

model2.add(Bidirectional(LSTM(100)))
model2.add(Dense(num_classes, activation='softmax'))

model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model2.fit(X_train, y_train, epochs=10, batch_size=64,
                    validation_data=(X_validation, y_validation), verbose=1)

Epoch 1/10
134/134 [==============================] - 19s 104ms/step - loss: 0.6111 - accuracy: 0.7046 - val_loss: 0.6178 - val_accuracy: 0.6926
Epoch 2/10
134/134 [==============================] - 11s 85ms/step - loss: 0.5980 - accuracy: 0.7060 - val_loss: 0.6157 - val_accuracy: 0.6888
Epoch 3/10
134/134 [==============================] - 11s 85ms/step - loss: 0.5853 - accuracy: 0.7078 - val_loss: 0.6101 - val_accuracy: 0.7002
Epoch 4/10
134/134 [==============================] - 11s 85ms/step - loss: 0.5711 - accuracy: 0.7129 - val_loss: 0.6053 - val_accuracy: 0.6964
Epoch 5/10
134/134 [==============================] - 12s 89ms/step - loss: 0.5491 - accuracy: 0.7244 - val_loss: 0.6052 - val_accuracy: 0.6983
Epoch 6/10
134/134 [==============================] - 14s 101ms/step - loss: 0.5249 - accuracy: 0.7430 - val_loss: 0.6044 - val_accuracy: 0.6736
Epoch 7/10
134/134 [==============================] - 13s 99ms/step - loss: 0.4997 - accuracy: 0.7565 - val_loss: 0.6522 - val_accurac